### ISSUE TITLE
wrong file called in 3.ledger example

### ISSUE THREAD

**Issue by mgass** [mikekchar/ledger-currencies#1]
beginning at line 86 in 3.ledger, the example command calls 2.ledger:

> ; Let run this report in JPY:
> ;  ledger -f 2.ledger -X JPY bal
> 
> ; Wait... That doesn't seem right.  It doesn't balance!
> ; There is a balance of 300 JPY left over.  Why?

I believe that the balance command should call 3.ledger, the file that includes lot prices. Correct me if I'm wrong. Using 2.ledger, which has no lot prices, shows no remainder/capital gains. Replacing the 2.ledger with 3.ledger produces the balance of 300 JPY refer to on line 90.

Your tutorial helped me. I'm grateful I came across it.

**Comment by mgass** [comment]
from 4.ledger, line 55-57:

> ; Important note: If you are calculating capital gains using
; average cost, you must do this very differently.  I will
; provide an example later.

I have a situation in which I need to use average cost, but I haven't found a satisfying means of implementing this method in ledger. How did you do it?

**Comment by mikekchar** [comment]
You are right!  Thanks.  I haven't looked at these in a long time.  I'll fix it :-)
